# Exclude SMPL/Plush since these are not used anymore
# Exclude included libraries
extraction:
    javascript:
        index:
            - exclude: interfaces/smpl
            - exclude: interfaces/Plush
            - exclude: "**/*jquery*"
            - exclude: "**/*min*"
    python:
        index:
            - exclude: cherrypy
            - exclude: gntp