class Status:
  COMPLETED = "Completed"
  EXTRACTING = "Extracting"
  FAILED = "Failed"
  FETCHING = "Fetching"
  MOVING = "Moving"
  PAUSED = "Paused"
  QUEUED = "Queued"
  QUICK_CHECK = "QuickCheck"
  REPAIRING = "Repairing"
  RUNNING = "Running"
  VERIFYING = "Verifying"  
