name: Feature request
description: What new feature would you like to have added to SABnzbd?
labels:
  - Support
body:
  - type: textarea
    attributes:
      label: Description
    validations:
      required: true
