name: sabnzbd
version: git
summary: SABnzbd
description: The automated Usenet download tool
confinement: strict
grade: devel
icon: interfaces/Config/templates/staticcfg/images/logo-small.svg
version-script: |
  grep -oP '(?<=^Version: ).*' PKG-INFO

apps:
  sabnzbd:
    environment:
      LC_CTYPE: C.UTF-8
    command: python $SNAP/opt/sabnzbd/SABnzbd.py -f $SNAP_COMMON
    daemon: simple
    plugs: [network, network-bind, removable-media]

parts:
  sabnzbd:
    plugin: python
    source: .
    python-version: python2
    python-packages: [cheetah3, cryptography, sabyenc]
    build-attributes: [no-system-libraries]
    stage-packages: [unrar, p7zip-full, par2]
    build-packages: [libffi-dev, python-dev, libssl-dev]
    override-build: |
      snapcraftctl build
      python tools/make_mo.py
      mkdir -p $SNAPCRAFT_PART_INSTALL/opt
      cp -R $SNAPCRAFT_PART_BUILD $SNAPCRAFT_PART_INSTALL/opt/sabnzbd
    organize:
      usr/bin/unrar-nonfree: usr/bin/unrar
