name: sabnzbd
summary: SABnzbd
description: The automated Usenet download tool
confinement: strict
base: core24
grade: stable
icon: interfaces/Config/templates/staticcfg/images/logo-small.svg
adopt-info: sabnzbd

architectures:
  - build-on: arm64
  - build-on: armhf
  - build-on: amd64

apps:
  sabnzbd:
    environment:
      PATH: $SNAP/usr/lib/p7zip:$PATH
      LC_CTYPE: C.UTF-8
      SNAPCRAFT_PRELOAD_REDIRECT_ONLY_SHM: 1
    command: bin/sabnzbd-wrapper
    daemon: simple
    plugs: [network, home, network-bind, removable-media]

parts:
  sabnzbd:
    plugin: python
    source: .
    requirements: [snap/local/requirements_snap.txt, requirements.txt]
    stage-packages: [python3-dev, libdb5.3, unrar, p7zip-full, par2]
    build-packages: [pkg-config, libffi-dev, python3-dev, libssl-dev, cargo]
    override-build: |
      craftctl set version=$(grep -o -P '(?<=__version__ = ").*(?=")' sabnzbd/version.py)
      craftctl build
      python3 tools/make_mo.py
      mkdir -p $SNAP_PART_INSTALL/opt
      cp -R $SNAP_PART_BUILD $SNAP_PART_INSTALL/opt/sabnzbd
      mkdir -p $SNAP_PART_INSTALL/bin
      echo "\$SNAP/usr/bin/snapcraft-preload python3 \$SNAP/opt/sabnzbd/SABnzbd.py -f \$SNAP_COMMON" > $SNAP_PART_INSTALL/bin/sabnzbd-wrapper
      chmod +x $SNAP_PART_INSTALL/bin/sabnzbd-wrapper
      ln -sf ../usr/lib/libsnapcraft-preload.so $SNAP_PART_INSTALL/lib/libsnapcraft-preload.so
    prime: [-usr/bin/7z,-usr/bin/7za,-usr/bin/7zr]
    organize:
      usr/bin/unrar-nonfree: usr/bin/unrar
  snapcraft-preload:
    source: https://github.com/sergiusens/snapcraft-preload.git
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr -DLIBPATH=/lib
    stage-packages:
      - to amd64:
        - lib32stdc++6
    build-packages:
      - to arm64:
        - g++-multilib-arm-linux-gnueabihf
        - gcc-multilib-arm-linux-gnueabihf
      - else:
        - gcc-multilib
        - g++-multilib
