name: sabnzbd
summary: SABnzbd
description: The automated Usenet download tool
confinement: strict
base: core24
grade: stable
icon: interfaces/Config/templates/staticcfg/images/logo-small.svg
adopt-info: sabnzbd

platforms:
  amd64:
  arm64:

apps:
  sabnzbd:
    environment:
      LC_CTYPE: C.UTF-8
      SNAPCRAFT_PRELOAD_REDIRECT_ONLY_SHM: 1
    command: usr/bin/snapcraft-preload python3 $SNAP/opt/sabnzbd/SABnzbd.py -f $SNAP_COMMON
    daemon: simple
    plugs: [network, home, network-bind, removable-media]

parts:
  sabnzbd:
    plugin: python
    source: .
    python-requirements:
      - requirements.txt
    stage-packages:
      - 7zip-standalone
    build-packages:
      - git
      - pkg-config
      - libffi-dev
      - python3-dev
      - libssl-dev
      - cargo
      - rsync
    override-pull: |
      craftctl default
      craftctl set version=$(grep -o -P '(?<=__version__ = ").*(?=")' sabnzbd/version.py)
      if [ -z "$(git status --porcelain)" ]; then
        COMMIT=$(git rev-parse --short HEAD)
        sed -i "s/__baseline__ = .*/__baseline__ = \"${COMMIT}\"/" sabnzbd/version.py
      fi
    override-build: |
      craftctl default
      python3 tools/make_mo.py
      rsync -av --mkpath \
        --exclude=.git \
        --exclude=.github \
        --exclude=builder \
        --exclude=macos \
        --exclude=po \
        --exclude=snap \
        --exclude=tests \
        --exclude=win \
        $CRAFT_PART_BUILD/ $CRAFT_PART_INSTALL/opt/sabnzbd/
      ln -sf ../usr/lib/libsnapcraft-preload.so $CRAFT_PART_INSTALL/lib/libsnapcraft-preload.so
      # 7-Zip script has an invalid path in a snap context
      rm -rf $CRAFT_PART_INSTALL/usr/bin/7zz
    organize:
      usr/lib/7zip/7zz: usr/bin/7zz
    prime:
      - -usr/lib/7zip
  par2cmdline-turbo:
    source: .
    plugin: autotools
    build-packages:
      - jq
      - curl
    build-environment:
      - LDFLAGS: -s
    override-pull: |
      PAR2_TARBALL=$(curl -sL https://api.github.com/repos/animetosho/par2cmdline-turbo/releases/latest | jq -r '.tarball_url')
      curl -o /tmp/par2cmdline.tar.gz -L $PAR2_TARBALL
      tar xf /tmp/par2cmdline.tar.gz --strip-components=1
    autotools-configure-parameters:
      - --prefix=/usr
  unrar:
    source: https://www.rarlab.com/rar/unrarsrc-7.1.10.tar.gz
    plugin: make
    override-build: |
      case $CRAFT_ARCH_BUILD_FOR in
        amd64)
          cxxflags=-march=native
          ;;
        arm64)
          cxxflags=-march=armv8-a+crypto+crc
          ;;
      esac
      sed -i "/^CXXFLAGS=/ s|$| ${cxxflags}|" makefile
      craftctl default
      $CRAFT_PART_INSTALL/bin/unrar || exit 1
  snapcraft-preload:
    source: https://github.com/sergiusens/snapcraft-preload.git
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
      - -DLIBPATH=/lib
    stage-packages:
      - to amd64:
        - lib32stdc++6
    build-packages:
      - to amd64:
        - gcc-multilib
        - g++-multilib
