name: sabnzbd
version: git
summary: SABnzbd
description: The automated Usenet download tool
grade: stable
confinement: strict

apps:
  sabnzbd:
    command: python $SNAP/opt/sabnzbd/SABnzbd.py -f $SNAP_COMMON
    daemon: simple
    plugs: [network, network-bind, removable-media]

parts:
  ppa:
    plugin: nil
    build-packages: [software-properties-common]
    override-build: |
      add-apt-repository -yu ppa:jcfp/sab-addons

  sabnzbd:
    after: [ppa]
    plugin: python
    source: .
    python-version: python2
    python-packages: [cheetah3, cryptography, sabyenc]
    stage-packages:
      - to armhf: ["unrar:armhf", "p7zip-full:armhf", "openssl:armhf", "par2:armhf"]
      - to arm64: ["unrar:arm64", "p7zip-full:arm64", "openssl:arm64", "par2:arm64"]
      - else: ["unrar", "p7zip-full", "openssl", "par2-tbb"]
    build-packages:
      - to armhf: ["libffi-dev:armhf", "python-dev:armhf", "libssl-dev:armhf"]
      - to arm64: ["libffi-dev:arm64", "python-dev:arm64", "libssl-dev:arm64"]
      - else: ["libffi-dev", "python-dev", "libssl-dev"]
    override-build: |
      snapcraftctl build
      python tools/make_mo.py
      mkdir -p $SNAPCRAFT_PART_INSTALL/opt/sabnzbd
      cp -R $SNAPCRAFT_PART_BUILD/* $SNAPCRAFT_PART_INSTALL/opt/sabnzbd
