name: Update translatable texts

on:
  push:
    branches:
    - develop

permissions:
  contents: write

jobs:
  translations:
    name: Update translatable texts
    runs-on: ubuntu-latest
    env:
      TX_TOKEN: ${{ secrets.TX_TOKEN }}
    steps:
      - uses: actions/checkout@v6
      - name: Generate translatable texts
        run: |
          python3 tools/extract_pot.py
      - name: Push/pull Transifex translations
        if: env.TX_TOKEN
        # We use fixed version and manual download (instead of their sh script) to prevent potential supply-chain attack.
        # Changes are commited directly to the repo, so this is quite sensative and worth the extra hassle!
        # Add --translation to the push command in order to update Transifex using local translation edits
        # However, this prevents modifying existing translations in Transifex as they will be overwritten by the push!
        run: |
          TX_VERSION="v1.6.17"
          curl -fsSL "https://github.com/transifex/cli/releases/download/${TX_VERSION}/tx-linux-amd64.tar.gz" -o tx-linux-amd64.tar.gz
          tar -xzf tx-linux-amd64.tar.gz
          ./tx push --source 
          ./tx pull --all --force
      - name: Compile translations to validate them
        run: |
          python3 tools/make_mo.py
      - name: Push translatable and translated texts back to repo
        if: env.TX_TOKEN
        run: |
          git config user.name "SABnzbd Automation"
          git config user.email "bugs@sabnzbd.org"
          git add po/*.pot po/*.po *.nsi
          git diff --cached --quiet || git commit -m "Update translatable texts" -m "[skip ci]"
          git push
