name: Update translatable texts

on:
  push:
    branches:
    - develop

jobs:
  translations:
    name: Update translatable texts
    runs-on: ubuntu-latest
    env:
      TX_TOKEN: ${{ secrets.TX_TOKEN }}
    steps:
      - uses: actions/checkout@v6
        with:
          token: ${{ secrets.AUTOMATION_GITHUB_TOKEN }}
      - name: Generate translatable texts
        run: |
          python3 tools/extract_pot.py
      - name: Push/pull Transifex translations
        if: env.TX_TOKEN
        # Add --translation to the push command in order to update Transifex using local translation edits
        # However, this prevents modifying existing translations in Transifex as they will be overwritten by the push!
        run: |
          curl -o- https://raw.githubusercontent.com/transifex/cli/master/install.sh | bash
          ./tx push --source 
          ./tx pull --all --force
      - name: Compile translations to validate them
        run: |
          python3 tools/make_mo.py
      - name: Push translatable and translated texts back to repo
        if: env.TX_TOKEN
        run: |
          git config user.name "SABnzbd Automation"
          git config user.email "bugs@sabnzbd.org"
          git add po/*.pot po/*.po *.nsi
          git diff --cached --quiet || git commit -m "Update translatable texts" -m "[skip ci]"
          git push
